stages:
- name: repo
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile
      buildContext: .
      tag: a349875/k8slab01:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
- name: test
  steps:
  - runScriptConfig:
      image: nginx
      shellScript: |2-
          #!/bin/bash
          if [ `curl -s -I  http://13.124.72.122:30717 | grep HTTP | awk {'print $2'}`=200 ]
          then
          exit 0
          else
          exit 1
          fi
- name: depoly
  steps:
  - applyYamlConfig:
      path: ./nginx-pod-update.yaml
timeout: 60
notification: {}
