stages:
- name: repo
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile
      buildContext: .
      tag: a349875/app:v3
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./nginx-pod.yaml
timeout: 60
notification: {}
