apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
   app: nginx-deployment
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30717
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx-v3
spec:
  replicas: 1
  selector:
    app: nginx
    deployment: v3
  template:
    metadata:
      labels:
        app: nginx
        deployment: v3
    spec:
      containers:
      - name: nginx
        image: a349875/k8slab01:v3
        args: ["nginx", "-T"]
        ports:
        - containerPort: 80
