apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels: 
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-container
        image: a349875/k8slab01:v3
        ports:
        - containerPort: 80
